#x=5
#print(type(x))
#x="hai"
#print(type(x))
#x=15
#print(type(x))
#x=25.5
#print(type(x))
#x=5j
#print(type(x))
#x=["chenchu","dreamer","winner"]
#print(type(x))
#x=("chenchu","dreamer","winner")
#print(type(x))
#x=range(8)
#print(x)
#print(type(x))
#x={"chenchu","dreamer","winner"}
#print(type(x))
#x={"name":"chenchu","blood":"A+"}
#print(type(x))
#x=frozenset({"chenchu","dreamer","winner"})
#print(type(x))
#x= True
#print(type(x))
#x=b"chenchu"
#print(type(x))
#x=bytearray(5)
#print(x)
#x=memoryview(bytes(5))
#print(type(x))
#x=range(6)
#print(x)
#print(type(x))